FROM debian:stretch
ARG release
ENV release=${release}
RUN apt-get -y update && apt-get install -y \
    libx11-dev \
    libpng-dev \
    libfftw3-dev \
    libcfitsio-dev \
    libforms-dev \
    python-dev \
    python-numpy \
    libgtk2.0-dev \
    gfortran \
    curl
RUN curl http://www.iram.fr/~gildas/dist/gildas-src-$release.tar.gz | tar xz && \
    bash -c "cd gildas-src-$release && \
    GAG_SEARCH_PATH=/usr/lib/x86_64-linux-gnu source admin/gildas-env.sh && \
    make && make -j 4 install" && \
    echo 'export GAG_ROOT_DIR=/gildas-exe-$release' >> /etc/bash.bashrc && \
    echo 'export GAG_EXEC_SYSTEM=x86_64-debian9-gfortran' >> /etc/bash.bashrc && \
    echo '. $GAG_ROOT_DIR/etc/bash_profile' >> /etc/bash.bashrc && \
    rm -Rf gildas-src-$release && \
    cd gildas-exe-$release && \
    curl http://www.iram.fr/~gildas/dist/gildas-doc-$release.tar.gz | tar xz
